# ===============================================================================
# 10 — CAPTURE THE ANALYSIS ENVIRONMENT
# ===============================================================================
# Writes the exact R and package versions that produced the results, so the deposit
# documents its own provenance rather than relying on versions transcribed into a
# Methods section by hand.
#
# WHY IT MATTERS MOST FOR THE ENRICHMENT FIGURES. GO term-to-gene mappings live in
# VERSIONED annotation snapshots (org.Mm.eg.db, GO.db). Which genes belong to a term
# changes between Bioconductor releases, so re-running 05 on a different release can
# return a different list of terms, not merely different p-values. The differential
# expression results are far more stable; the GO panels are the fragile part.
#
# Run this LAST; it attaches every package the pipeline uses so the capture covers
# the whole stack rather than whatever happened to be loaded.
#
# renv.lock is the companion to this file: this one DOCUMENTS the environment, renv
# RESTORES it. Keep both.
#
# Output: results/sessionInfo.txt
# ===============================================================================

PKGS <- c(
  # differential expression and statistics
  "DESeq2", "limma", "apeglm", "sandwich", "lmtest",
  # annotation and enrichment
  "biomaRt", "clusterProfiler", "org.Mm.eg.db", "GO.db", "AnnotationDbi",
  # io and figures
  "openxlsx", "ggplot2", "ggrepel", "pheatmap", "VennDiagram", "scales", "futile.logger")

out_dir <- file.path(getwd(), "results")
if (!dir.exists(out_dir)) dir.create(out_dir, recursive = TRUE)

missing <- PKGS[!vapply(PKGS, requireNamespace, logical(1), quietly = TRUE)]
if (length(missing))
  warning("not installed, so absent from the capture: ", paste(missing, collapse = ", "),
          call. = FALSE)
invisible(lapply(setdiff(PKGS, missing), function(p)
  suppressPackageStartupMessages(library(p, character.only = TRUE))))

f <- file.path(out_dir, "sessionInfo.txt")
con <- file(f, open = "wt")
writeLines(c(
  "Environment that produced the results in this directory.",
  "Generated by scripts/10_session_info.R — do not edit by hand.",
  "",
  "NOTE: org.Mm.eg.db and GO.db are versioned annotation snapshots. GO term",
  "membership changes between Bioconductor releases, so the enrichment figures",
  "(script 04) are the outputs most sensitive to the versions below.",
  "", strrep("-", 78), ""), con)
capture.output(sessionInfo(), file = con, append = TRUE)
close(con)

cat(sprintf("Saved: results/sessionInfo.txt  (R %s.%s, %d packages captured)\n",
            R.version$major, R.version$minor, length(setdiff(PKGS, missing))))
for (p in c("DESeq2", "clusterProfiler", "org.Mm.eg.db", "GO.db"))
  if (p %in% setdiff(PKGS, missing))
    cat(sprintf("  %-18s %s\n", p, as.character(packageVersion(p))))
